source "https://rubygems.org"

gem "rake"
gem "middleman", "~> 4.1"
gem "middleman-deploy", github: "middleman-contrib/middleman-deploy"
gem "middleman-livereload", "~> 3.4.0"
gem "middleman-syntax"
gem "middleman-sprockets", "~> 4.1"
gem "slim"
gem "compass"
gem "semantic-ui-sass", "2.4.2.0", require: false
gem "redcarpet"
gem "sprockets", "< 4"
