source "https://rubygems.org"

gem "rake"
gem "middleman", "~> 3.4"
gem "middleman-deploy"
gem "middleman-livereload", "~> 3.4.0"
gem 'middleman-syntax'
gem "slim"
gem "compass"
gem "semantic-ui-sass"
gem "redcarpet"

